### PR TITLE
Editorial

### PR DESCRIPTION
**Pull request by munrocket**
1) Mark that CanIUse shows support only for MVP. Or maybe place this in FAQ?
2) Make italic text without bold style for "More examples"

### CODE REVIEW

**Comment by MaxGraey** [comment]
1. It's much longer than before. Is it really need emphasise MVP status? 
2. You could just use single `*` for make non-bold italic instead using `<em>`

**Comment by munrocket** [comment]
It is not obvious that there are different versions of Wasm and CanIUse shows only MVP.
It can be formulated in another way. Maybe a link to https://webassembly.org/roadmap/ or somehow.

**Comment by MaxGraey** [comment]
https://webassembly.org/roadmap/  link [already exists](https://github.com/WebAssembly-Enthusiasts/info/tree/master/resources#proposals)

**Comment by munrocket** [comment]
So it can be in another section. It's just an Idea how to show this in another way.

**Webassembly Support**
* [MVP](https://caniuse.com/#search=wasm)
* [Post-MVP](https://webassembly.org/roadmap/)

**Comment by MaxGraey** [comment]
I don't think we should focused on MVP, non-MVP. This may confuse someone who is not yet familiar with it.

**Pull request closed without merging**
